version: '3'
services:
  postgis:
    image: kartoza/postgis:9.6-2.4
    container_name: postgis
    environment:
      - POSTGRES_DB=gis
      - POSTGRES_USER=docker
      - POSTGRES_PASS=docker
      - ALLOW_IP_RANGE=0.0.0.0/0
    ports:
       - "5432:5432"
    restart: unless-stopped