openapi: "3.0.0"
info:
  title: Geoimagenet API
  description: API for Geoimagenet
  version: 1.0.0
servers:
  - url: /api/v1
    description: Production server
paths:
  /:
    get:
      summary: General information about the api
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiInfo'
  /users:
    get:
      summary: Search users
      parameters:
        - name: username
          in: query
          schema:
            type: string
        - name: name
          in: query
          schema:
            type: string
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'
        404:
          description: Not found
          content:
            application/json: {}
    post:
      summary: Add a user
      parameters:
        - name: username
          in: query
          required: true
          schema:
            type: string
        - name: name
          in: query
          required: true
          schema:
            type: string
      responses:
        201:
          description: The person created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
  /users/{username}:
    get:
      summary: Get a user by username
      parameters:
        - name: username
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        404:
          description: Not found
          content:
            application/json: {}
  /taxonomy_classes:
    get:
      summary: Search taxonomy class elements
      parameters:
        - name: taxonomy_name
          in: query
          required: true
          schema:
            type: string
        - name: id
          in: query
          schema:
            type: integer
        - name: name
          in: query
          schema:
            type: string
        - name: depth
          in: query
          description: The depth of taxonomy class children to return. -1 means infinite and is the default.
          schema:
            type: integer
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TaxonomyClass'
        404:
          description: Not found
          content:
            application/json: {}

  /taxonomy_classes/{id}:
    get:
      summary: Get a specific taxonomy class by id
      parameters:
        - name: id
          in: path
          description: The id of the taxonomy class
          required: true
          schema:
            type: integer
        - name: depth
          in: query
          description: The depth of taxonomy class children to return. -1 means infinite and is the default.
          schema:
            type: integer
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TaxonomyClass'
        404:
          description: Not found
          content:
            application/json: {}

  /taxonomy:
    get:
      summary: Search taxonomy elements
      parameters:
        - name: name
          in: query
          description: Full name or sluggified name of the taxonomy
          schema:
            type: string
        - name: version
          description: The version of the taxonomy. `name` is required if version is provided.
          in: query
          schema:
            type: string
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/TaxonomyGroup'
        404:
          description: Not found
          content:
            application/json: {}
        400:
          description: Bad request
          content:
            application/json: {}

  /taxonomy/{name_slug}/{version}:
    get:
      summary: 'Get a specific taxonomy by name slug and version'
      description: 'Example of name slug for "Couverture de sol": couverture-de-sol'
      operationId: geoimagenet_api.routes.taxonomy.get_by_slug
      parameters:
        - name: name_slug
          in: path
          description: The name slug of the taxonomy
          required: true
          schema:
            type: string
        - name: version
          in: path
          description: The version of the taxonomy
          required: true
          schema:
            type: string
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Taxonomy'
        404:
          description: Not found
          content:
            application/json: {}

  /validations:
    get:
      summary: Search validations
      tags:
        - not implemented
      parameters:
        - name: annotation_id
          in: query
          description: The id of the annotation that was validated
          schema:
            type: integer
        - name: validator_id
          in: query
          description: The id of the person that validated
          schema:
            type: integer
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Validation'
        404:
          description: Not found
          content:
            application/json: {}
    post:
      summary: Validate annotations
      tags:
        - not implemented
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ValidationPost'
      responses:
        201:
          description: The validations created
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Validation'

  /annotations:
    put:
      summary: Update annotations
      requestBody:
        content:
          application/json:
            schema:
              description: GeoJson annotation to be modified
              $ref: '#/components/schemas/GeoJsonAnnotation'
      responses:
        204:
          description: No Content
        404:
          description: Annotation not found
          content:
            application/json: {}
    post:
      summary: Write an annotation to the database
      requestBody:
        content:
          application/json:
            schema:
              description: GeoJson annotation to be written to the database
              $ref: '#/components/schemas/GeoJsonAnnotation'
      responses:
        201:
          description: The id of the created annotation
          content:
            application/json:
              schema:
                description: List containing the database ids created
                type: array
                items:
                  type: integer

components:
  schemas:
    ApiInfo:
      type: object
      additionalProperties: false
      properties:
        name:
          type: string
        version:
          type: string
        authors:
          type: string
        email:
          type: string
        documetation_url:
          type: string
    GeoJsonAnnotation:
      type: object
      additionalProperties: false
      required:
        - type
        - geometry
        - properties
      properties:
        type:
          type: string
        geometry:
          $ref: '#/components/schemas/Geometry'
        properties:
          $ref: '#/components/schemas/AnnotationProperties'
    Geometry:
      type: object
      additionalProperties: false
      required:
        - type
        - coordinates
      properties:
        type:
          type: string
        coordinates:
          oneOf:
            - type: array
              items:
                type: number
            - type: array
              items:
                type: array
                items:
                  type: number
            - type: array
              items:
                type: array
                items:
                  type: array
                  items:
                    type: number
    AnnotationProperties:
      type: object
      additionalProperties: false
      required:
        - annotator_id
        - taxonomy_class_id
        - image_name
      properties:
        annotator_id:
          type: integer
        taxonomy_class_id:
          type: integer
        image_name:
          type: string
        annotation_id:
          type: integer
        released:
          type: boolean
    User:
      type: object
      required:
        - id
        - username
        - name
      properties:
        id:
          type: integer
          format: int64
        username:
          type: string
        name:
          type: string
    TaxonomyClass:
      type: object
      required:
        - id
        - name
        - taxonomy_id
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        taxonomy_id:
          type: integer
          format: int64
        children:
          type: array
          items:
            $ref: '#/components/schemas/TaxonomyClass'
    Taxonomy:
      type: object
      required:
        - id
        - name
        - slug
        - version
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        slug:
          type: string
        version:
          type: string
    TaxonomyGroup:
      type: object
      required:
        - name
        - slug
        - versions
      properties:
        name:
          type: string
        slug:
          type: string
        versions:
          type: array
          items:
            $ref: '#/components/schemas/TaxonomyVersion'
    TaxonomyVersion:
      type: object
      required:
        - taxonomy_id
        - version
      properties:
        taxonomy_id:
          type: integer
          format: int64
        version:
          type: string
    Validation:
      type: object
      required:
        - id
        - annotation_id
        - validator_id
      properties:
        id:
          type: integer
          format: int64
        annotation_id:
          type: integer
          format: int64
        validator_id:
          type: integer
          format: int64
        created_at:
          type: string
          format: date-time
    ValidationPost:
      type: object
      required:
        - annotation_ids
        - validator_id
      properties:
        annotation_ids:
          type: array
          items:
            type: integer
        validator_id:
          type: integer
          format: int64