# Paths can be relative to this file or absolute

# Base path with the folders containing raster images
images_folder: /images_folder

# Create the cached layers or not on the datastore
create_cached_layers: true

# A list of styles to upload on the server
# The default style located in ./styles/DEFAULT_RASTER.xml will always be added
styles:
  - name: RGB
    path: ./styles/RGB.xml
  - name: NRG
    path: ./styles/NRG.xml

metadata:
  - name: PLEIADES
    attribution: © Airbus DS (2019)